### ISSUE TITLE
update instructions to use new/quick nimbix sign-on

### ISSUE THREAD

**Issue by stevemart** [IBM/powerai-notebook#13]

**Comment by zamrokk** [comment]
i sent an email to the support as the form was not working and they opened me an account. They ask after for a credit card.

**Comment by zamrokk** [comment]
![image](https://cloud.githubusercontent.com/assets/2536368/26412838/529301d6-40aa-11e7-9a98-e43e702b6099.png)

**Comment by zamrokk** [comment]
Is there a way to have a free sandbox environment ? I fear this will not encourage people to test the journey.

**Comment by stevemart** [comment]
hey @zamrokk -- we're actually updating the instructions in #14 -- care to try them out? it should allow folks to sign up without a credit card...

**Comment by rhagarty** [comment]
Readme has been updated with new instructions on how to registration for getting Nimbix trial account to run this journey.

**Comment by stevemart** [comment]
closing since #14 merged
